# -*- coding: utf-8 -*-
"""magic_square.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jPy6TeCWo3-jbUWBLvO5pzAramJsh0Yg
"""

import numpy as np

N  = 3
magic_square = np.zeros((N,N), dtype=int)

n = 1
i, j = 0, N//2

while n <= N**2:
    magic_square[i, j] = n
    n += 1
    new_i, new_j = (i-1) % N, (j+1)% N
    if magic_square[new_i, new_j]:
        i += 1
    else:
        i, j = new_i, new_j

print(magic_square)

a=[]
for i in range(3):
  b=[]
  for j in range(3):
    j= int(input("Enter a number "))
    b.append(j)
  a.append(b)
print("Matrix is : ")

for i in range(3):
  for j in range(3):
    print(a[i][j], end=" ")
  print()

sum1=0
sum2=0
for i in range(3):
  for j in range(3):
    if i==j :
      sum1 += a[i][j]
      if i+j== 3-1:
        sum2 += a[i][j]

if sum1!= sum2:
  flag=1
else:
  for i in range(3):
    row_sum=0
    col_sum=0
    for j in range(3):
      row_sum += a[i][j]
      col_sum += a[j][i]
    if row_sum!= sum1:
      flag =1
    elif col_sum !=sum1:
      flag=1
    else:
      flag=0

if flag==0:
  print("Matrix is magic sqaure")
else:
  print("Matrix is not magic square")